@startuml databaseumlER

enum Currency {
  USD
  EUR
  CHF
  ...
}

enum ExpenseCategory {
  FOOD
  TRANSPORT
  HOUSING
  UTILITIES
  OTHER
}

class "Group" {
  {static} id: string/uuid
  linkToken: string/uuid
  name: string
  description: string
  currency: Currency
  users: UserIndex
  
  creationDate: date
  lastUpdated: date
  version: int
  --
  ** Computable values **
  totalExpenses: float
  userExpenses: float[]
  balanceExpenses: json?
  expensesPrediction: TBD
}

note top of Group
    Check if better to store computable
    values or recompute them each time
end note

class "Expense" {
  {static} id: int
  name: string
  category: ExpenseCategory
  currency: Currency
  exchange_rate: float
  date: date
  amount: float
  
  creationDate: date
  lastUpdated: date
  version: int

  paidBy: PaidDetails
  paidFor: PaidDetails
}

Group "1" -- "*" Expense

/'Comment all below if your visualiser doesn't support json'/

json "PaidDetails" {
  "repartitionType": "\"equal\" | \"portions\" | \"amount\"",
  "repartition": "['userId': int; 'values': { 'amount?':float, 'share?':float }, ...]"
}

"PaidDetails" -l[hidden]- Expense

json "UserIndex" {
    "id":"int",
    "name":"str"
    /'"indexes" : "[{'id':int; 'name':str}, ...]",'/
    /'"maybeExpenses?":"",'/
    /'"maybeBalances?":""'/
}

UserIndex -l[hidden]- Group

note right of UserIndex
    Check if better to store user expenses
    and balances in two attributes
    or in one json object
end note

@enduml