architecture-beta
    group frontend[Frontend]

    service playstore(logos:google-play-icon)[Playstore] in frontend
    service appstore(logos:apple-app-store)[Appstore] in frontend
    service website(logos:firefox)[Website] in frontend

    group CICD[CICD]

    service github(logos:github-actions)[Actions pipeline] in CICD

    github{group}:R -- L:playstore{group}

    %% group api(cloud)[API]

    %% service db(database)[Database] in api
    %% service server(server)[Server] in api

    %% %% db:L -[hidden]-> R:server
    %% db:B -- T:server