architecture-beta

    group backendcode[Development]

    service nestjs(logos:nestjs)[NestJS] in backendcode
    service postgres(logos:postgresql)[PostgreSQL] in backendcode
    service typeorm(logos:typeorm)[TypeORM] in backendcode

    group cicd(logos:github-actions)[Github Actions pipeline]

    service jest(logos:jest)[Jest] in cicd
    service docker(logos:docker)[Docker] in cicd

    jest:R -- L:docker

    group api(cloud)[API]

    service dockercompose(logos:docker)[Docker Compose] in api
    service buddycountapi(logos:aws-api-gateway)[BuddyCount API] in api
    service traefik(logos:nginx)[Traefik] in api
    service swagger(logos:swagger)[Swagger] in api
    service adminer(logos:aws-rds)[Adminer] in api

    dockercompose:R -- L:traefik
    traefik:T -- B:adminer
    traefik:R -- L:buddycountapi
    traefik:B -- T:swagger


    %% Links between groups
    nestjs{group}:B -- T:docker{group}
    jest{group}:B -- T:dockercompose{group}

    %% service db(database)[Database] in api
    %% service server(server)[Server] in api

    %% %% db:L -[hidden]-> R:server
    %% db:B -- T:server